# Generated by Django 5.2.4 on 2025-07-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_address', models.TextField()),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_address', models.TextField()),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('actual_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chargable_weight', models.CharField(max_length=100)),
                ('number_of_box', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service', models.CharField(max_length=100)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('status', models.CharField(choices=[('Shipment Booked', 'Shipment Booked'), ('Pickup Scheduled', 'Pickup Scheduled'), ('Picked Up ', 'Picked Up '), ('Shipment Collected at Origin', 'Shipment Collected at Origin'), ('Shipment Received at Origin Facility ', 'Shipment Received at Origin Facility'), ('Processing at Origin Hub', 'Processing at Origin Hub'), ('Departed from Origin Country', 'Departed from Origin Country'), ('In Transit to Destination Country', 'In Transit to Destination Country'), ('Arrived at Transit Hub', 'Arrived at Transit Hub'), ('Departed from Transit Hub', 'Departed from Transit Hub'), ('Flight Delayed - Weather/Customs/Operations', 'Flight Delayed - Weather/Customs/Operations'), ('Arrived at Destination Country', 'Arrived at Destination Country'), ('Under Customs Inspection', 'Under Customs Inspection'), ('Clearance in Progress', 'Clearance in Progress'), ('Customs Cleared', 'Customs Cleared'), ('Held at Customs - Awaiting Documents', 'Held at Customs - Awaiting Documents'), ('Out for Delivery', 'Out for Delivery'), ('Delivery Attempted - Receiver Not Available', 'Delivery Attempted - Receiver Not Available'), ('Rescheduled for Delivery', 'Rescheduled for Delivery'), ('Delivered', 'Delivered'), ('Shipment on Hold - Pending Customs duty & tax', 'Shipment on Hold - Pending Customs duty & tax '), ('Customs Delay - Missing Documents', 'Customs Delay - Missing Documents'), ('Incorrect Address - Delivery Rescheduled', 'Incorrect Address - Delivery Rescheduled'), ('Returned to Origin', 'Returned to Origin'), ('Cancelled', 'Cancelled'), ('Shipment on Hold - Pending Shipping Charge', 'Shipment on Hold - Pending Shipping Charge'), ('Shipment on Hold - Awaiting Customs Instructions', 'Shipment on Hold - Awaiting Customs Instructions')], default='Shipment Booked', max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='label/')),
            ],
        ),
        migrations.CreateModel(
            name='LabelStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Shipment Booked', 'Shipment Booked'), ('Pickup Scheduled', 'Pickup Scheduled'), ('Picked Up ', 'Picked Up '), ('Shipment Collected at Origin', 'Shipment Collected at Origin'), ('Shipment Received at Origin Facility ', 'Shipment Received at Origin Facility'), ('Processing at Origin Hub', 'Processing at Origin Hub'), ('Departed from Origin Country', 'Departed from Origin Country'), ('In Transit to Destination Country', 'In Transit to Destination Country'), ('Arrived at Transit Hub', 'Arrived at Transit Hub'), ('Departed from Transit Hub', 'Departed from Transit Hub'), ('Flight Delayed - Weather/Customs/Operations', 'Flight Delayed - Weather/Customs/Operations'), ('Arrived at Destination Country', 'Arrived at Destination Country'), ('Under Customs Inspection', 'Under Customs Inspection'), ('Clearance in Progress', 'Clearance in Progress'), ('Customs Cleared', 'Customs Cleared'), ('Held at Customs - Awaiting Documents', 'Held at Customs - Awaiting Documents'), ('Out for Delivery', 'Out for Delivery'), ('Delivery Attempted - Receiver Not Available', 'Delivery Attempted - Receiver Not Available'), ('Rescheduled for Delivery', 'Rescheduled for Delivery'), ('Delivered', 'Delivered'), ('Shipment on Hold - Pending Customs duty & tax', 'Shipment on Hold - Pending Customs duty & tax '), ('Customs Delay - Missing Documents', 'Customs Delay - Missing Documents'), ('Incorrect Address - Delivery Rescheduled', 'Incorrect Address - Delivery Rescheduled'), ('Returned to Origin', 'Returned to Origin'), ('Cancelled', 'Cancelled'), ('Shipment on Hold - Pending Shipping Charge', 'Shipment on Hold - Pending Shipping Charge'), ('Shipment on Hold - Awaiting Customs Instructions', 'Shipment on Hold - Awaiting Customs Instructions')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='label_app.shippinglabel')),
            ],
        ),
    ]
