# Generated by Django 5.2.4 on 2026-01-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelstatushistory',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippinglabel',
            name='status',
            field=models.CharField(default='Shipment Booked', max_length=255),
        ),
    ]
