# Generated by Django 5.2.4 on 2026-01-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_app', '0003_alter_labelstatushistory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelstatushistory',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippinglabel',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
